import * as cloudApi from '.'
export const GroupMappingServiceClient = cloudApi.organizationmanager.group_mapping_service.GroupMappingServiceClient;
export const GroupServiceClient = cloudApi.organizationmanager.group_service.GroupServiceClient;
export const OrganizationServiceClient = cloudApi.organizationmanager.organization_service.OrganizationServiceClient;
export const SshCertificateServiceClient = cloudApi.organizationmanager.ssh_certificate_service.SshCertificateServiceClient;
export const UserServiceClient = cloudApi.organizationmanager.user_service.UserServiceClient;
export const OmCertificateServiceClient = cloudApi.organizationmanager.certificate_service.CertificateServiceClient;
export const FederationServiceClient = cloudApi.organizationmanager.federation_service.FederationServiceClient;