/* eslint-disable */
import { Timestamp } from "@yandex-cloud/core/dist/generated/google/protobuf/timestamp";
import Long from "long";
import _m0 from "protobufjs/minimal";
import { messageTypeRegistry } from "../../../../typeRegistry";

export const protobufPackage = "yandex.cloud.compute.v1";

/** An Image resource. */
export interface Image {
  $type: "yandex.cloud.compute.v1.Image";
  /** ID of the image. */
  id: string;
  /** ID of the folder that the image belongs to. */
  folderId: string;
  createdAt?:
    | Date
    | undefined;
  /** Name of the image. 1-63 characters long. */
  name: string;
  /** Description of the image. 0-256 characters long. */
  description: string;
  /** Resource labels as `key:value` pairs. Maximum of 64 per resource. */
  labels: { [key: string]: string };
  /**
   * The name of the image family to which this image belongs.
   *
   * You can get the most recent image from a family by using
   * the [yandex.cloud.compute.v1.ImageService.GetLatestByFamily] request
   * and create the disk from this image.
   */
  family: string;
  /** The size of the image, specified in bytes. */
  storageSize: number;
  /** Minimum size of the disk which will be created from this image. */
  minDiskSize: number;
  /**
   * License IDs that indicate which licenses are attached to this resource.
   * License IDs are used to calculate additional charges for the use of the virtual machine.
   *
   * The correct license ID is generated by the platform. IDs are inherited by new resources created from this resource.
   *
   * If you know the license IDs, specify them when you create the image.
   * For example, if you create a disk image using a third-party utility and load it into Object Storage, the license IDs will be lost.
   * You can specify them in the [yandex.cloud.compute.v1.ImageService.Create] request.
   */
  productIds: string[];
  /** Current status of the image. */
  status: Image_Status;
  /** Operating system that is contained in the image. */
  os?:
    | Os
    | undefined;
  /** When true, indicates there is an image pool for fast creation disks from the image. */
  pooled: boolean;
}

export enum Image_Status {
  STATUS_UNSPECIFIED = 0,
  /** CREATING - Image is being created. */
  CREATING = 1,
  /** READY - Image is ready to use. */
  READY = 2,
  /** ERROR - Image encountered a problem and cannot operate. */
  ERROR = 3,
  /** DELETING - Image is being deleted. */
  DELETING = 4,
  UNRECOGNIZED = -1,
}

export function image_StatusFromJSON(object: any): Image_Status {
  switch (object) {
    case 0:
    case "STATUS_UNSPECIFIED":
      return Image_Status.STATUS_UNSPECIFIED;
    case 1:
    case "CREATING":
      return Image_Status.CREATING;
    case 2:
    case "READY":
      return Image_Status.READY;
    case 3:
    case "ERROR":
      return Image_Status.ERROR;
    case 4:
    case "DELETING":
      return Image_Status.DELETING;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Image_Status.UNRECOGNIZED;
  }
}

export function image_StatusToJSON(object: Image_Status): string {
  switch (object) {
    case Image_Status.STATUS_UNSPECIFIED:
      return "STATUS_UNSPECIFIED";
    case Image_Status.CREATING:
      return "CREATING";
    case Image_Status.READY:
      return "READY";
    case Image_Status.ERROR:
      return "ERROR";
    case Image_Status.DELETING:
      return "DELETING";
    case Image_Status.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Image_LabelsEntry {
  $type: "yandex.cloud.compute.v1.Image.LabelsEntry";
  key: string;
  value: string;
}

export interface Os {
  $type: "yandex.cloud.compute.v1.Os";
  /**
   * Operating system type. The default is `LINUX`.
   *
   * This field is used to correctly emulate a vCPU and calculate the cost of using an instance.
   */
  type: Os_Type;
}

export enum Os_Type {
  TYPE_UNSPECIFIED = 0,
  /** LINUX - Linux operating system. */
  LINUX = 1,
  /** WINDOWS - Windows operating system. */
  WINDOWS = 2,
  UNRECOGNIZED = -1,
}

export function os_TypeFromJSON(object: any): Os_Type {
  switch (object) {
    case 0:
    case "TYPE_UNSPECIFIED":
      return Os_Type.TYPE_UNSPECIFIED;
    case 1:
    case "LINUX":
      return Os_Type.LINUX;
    case 2:
    case "WINDOWS":
      return Os_Type.WINDOWS;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Os_Type.UNRECOGNIZED;
  }
}

export function os_TypeToJSON(object: Os_Type): string {
  switch (object) {
    case Os_Type.TYPE_UNSPECIFIED:
      return "TYPE_UNSPECIFIED";
    case Os_Type.LINUX:
      return "LINUX";
    case Os_Type.WINDOWS:
      return "WINDOWS";
    case Os_Type.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

function createBaseImage(): Image {
  return {
    $type: "yandex.cloud.compute.v1.Image",
    id: "",
    folderId: "",
    createdAt: undefined,
    name: "",
    description: "",
    labels: {},
    family: "",
    storageSize: 0,
    minDiskSize: 0,
    productIds: [],
    status: 0,
    os: undefined,
    pooled: false,
  };
}

export const Image = {
  $type: "yandex.cloud.compute.v1.Image" as const,

  encode(message: Image, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.folderId !== "") {
      writer.uint32(18).string(message.folderId);
    }
    if (message.createdAt !== undefined) {
      Timestamp.encode(toTimestamp(message.createdAt), writer.uint32(26).fork()).ldelim();
    }
    if (message.name !== "") {
      writer.uint32(34).string(message.name);
    }
    if (message.description !== "") {
      writer.uint32(42).string(message.description);
    }
    Object.entries(message.labels).forEach(([key, value]) => {
      Image_LabelsEntry.encode(
        { $type: "yandex.cloud.compute.v1.Image.LabelsEntry", key: key as any, value },
        writer.uint32(50).fork(),
      ).ldelim();
    });
    if (message.family !== "") {
      writer.uint32(58).string(message.family);
    }
    if (message.storageSize !== 0) {
      writer.uint32(64).int64(message.storageSize);
    }
    if (message.minDiskSize !== 0) {
      writer.uint32(72).int64(message.minDiskSize);
    }
    for (const v of message.productIds) {
      writer.uint32(82).string(v!);
    }
    if (message.status !== 0) {
      writer.uint32(88).int32(message.status);
    }
    if (message.os !== undefined) {
      Os.encode(message.os, writer.uint32(98).fork()).ldelim();
    }
    if (message.pooled === true) {
      writer.uint32(104).bool(message.pooled);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Image {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseImage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.folderId = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.createdAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.name = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.description = reader.string();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          const entry6 = Image_LabelsEntry.decode(reader, reader.uint32());
          if (entry6.value !== undefined) {
            message.labels[entry6.key] = entry6.value;
          }
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.family = reader.string();
          continue;
        case 8:
          if (tag !== 64) {
            break;
          }

          message.storageSize = longToNumber(reader.int64() as Long);
          continue;
        case 9:
          if (tag !== 72) {
            break;
          }

          message.minDiskSize = longToNumber(reader.int64() as Long);
          continue;
        case 10:
          if (tag !== 82) {
            break;
          }

          message.productIds.push(reader.string());
          continue;
        case 11:
          if (tag !== 88) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        case 12:
          if (tag !== 98) {
            break;
          }

          message.os = Os.decode(reader, reader.uint32());
          continue;
        case 13:
          if (tag !== 104) {
            break;
          }

          message.pooled = reader.bool();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Image {
    return {
      $type: Image.$type,
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      folderId: isSet(object.folderId) ? globalThis.String(object.folderId) : "",
      createdAt: isSet(object.createdAt) ? fromJsonTimestamp(object.createdAt) : undefined,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      labels: isObject(object.labels)
        ? Object.entries(object.labels).reduce<{ [key: string]: string }>((acc, [key, value]) => {
          acc[key] = String(value);
          return acc;
        }, {})
        : {},
      family: isSet(object.family) ? globalThis.String(object.family) : "",
      storageSize: isSet(object.storageSize) ? globalThis.Number(object.storageSize) : 0,
      minDiskSize: isSet(object.minDiskSize) ? globalThis.Number(object.minDiskSize) : 0,
      productIds: globalThis.Array.isArray(object?.productIds)
        ? object.productIds.map((e: any) => globalThis.String(e))
        : [],
      status: isSet(object.status) ? image_StatusFromJSON(object.status) : 0,
      os: isSet(object.os) ? Os.fromJSON(object.os) : undefined,
      pooled: isSet(object.pooled) ? globalThis.Boolean(object.pooled) : false,
    };
  },

  toJSON(message: Image): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.folderId !== "") {
      obj.folderId = message.folderId;
    }
    if (message.createdAt !== undefined) {
      obj.createdAt = message.createdAt.toISOString();
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.labels) {
      const entries = Object.entries(message.labels);
      if (entries.length > 0) {
        obj.labels = {};
        entries.forEach(([k, v]) => {
          obj.labels[k] = v;
        });
      }
    }
    if (message.family !== "") {
      obj.family = message.family;
    }
    if (message.storageSize !== 0) {
      obj.storageSize = Math.round(message.storageSize);
    }
    if (message.minDiskSize !== 0) {
      obj.minDiskSize = Math.round(message.minDiskSize);
    }
    if (message.productIds?.length) {
      obj.productIds = message.productIds;
    }
    if (message.status !== 0) {
      obj.status = image_StatusToJSON(message.status);
    }
    if (message.os !== undefined) {
      obj.os = Os.toJSON(message.os);
    }
    if (message.pooled === true) {
      obj.pooled = message.pooled;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Image>, I>>(base?: I): Image {
    return Image.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Image>, I>>(object: I): Image {
    const message = createBaseImage();
    message.id = object.id ?? "";
    message.folderId = object.folderId ?? "";
    message.createdAt = object.createdAt ?? undefined;
    message.name = object.name ?? "";
    message.description = object.description ?? "";
    message.labels = Object.entries(object.labels ?? {}).reduce<{ [key: string]: string }>((acc, [key, value]) => {
      if (value !== undefined) {
        acc[key] = globalThis.String(value);
      }
      return acc;
    }, {});
    message.family = object.family ?? "";
    message.storageSize = object.storageSize ?? 0;
    message.minDiskSize = object.minDiskSize ?? 0;
    message.productIds = object.productIds?.map((e) => e) || [];
    message.status = object.status ?? 0;
    message.os = (object.os !== undefined && object.os !== null) ? Os.fromPartial(object.os) : undefined;
    message.pooled = object.pooled ?? false;
    return message;
  },
};

messageTypeRegistry.set(Image.$type, Image);

function createBaseImage_LabelsEntry(): Image_LabelsEntry {
  return { $type: "yandex.cloud.compute.v1.Image.LabelsEntry", key: "", value: "" };
}

export const Image_LabelsEntry = {
  $type: "yandex.cloud.compute.v1.Image.LabelsEntry" as const,

  encode(message: Image_LabelsEntry, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Image_LabelsEntry {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseImage_LabelsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Image_LabelsEntry {
    return {
      $type: Image_LabelsEntry.$type,
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: Image_LabelsEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Image_LabelsEntry>, I>>(base?: I): Image_LabelsEntry {
    return Image_LabelsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Image_LabelsEntry>, I>>(object: I): Image_LabelsEntry {
    const message = createBaseImage_LabelsEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

messageTypeRegistry.set(Image_LabelsEntry.$type, Image_LabelsEntry);

function createBaseOs(): Os {
  return { $type: "yandex.cloud.compute.v1.Os", type: 0 };
}

export const Os = {
  $type: "yandex.cloud.compute.v1.Os" as const,

  encode(message: Os, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.type !== 0) {
      writer.uint32(8).int32(message.type);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Os {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOs();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Os {
    return { $type: Os.$type, type: isSet(object.type) ? os_TypeFromJSON(object.type) : 0 };
  },

  toJSON(message: Os): unknown {
    const obj: any = {};
    if (message.type !== 0) {
      obj.type = os_TypeToJSON(message.type);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Os>, I>>(base?: I): Os {
    return Os.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Os>, I>>(object: I): Os {
    const message = createBaseOs();
    message.type = object.type ?? 0;
    return message;
  },
};

messageTypeRegistry.set(Os.$type, Os);

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in Exclude<keyof T, "$type">]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P> | "$type">]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = date.getTime() / 1_000;
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { $type: "google.protobuf.Timestamp", seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function longToNumber(long: Long): number {
  if (long.gt(globalThis.Number.MAX_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  return long.toNumber();
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
