/* eslint-disable */
import { Timestamp } from "@yandex-cloud/core/dist/generated/google/protobuf/timestamp";
import Long from "long";
import _m0 from "protobufjs/minimal";
import { messageTypeRegistry } from "../../../../typeRegistry";

export const protobufPackage = "yandex.cloud.compute.v1";

/** A Snapshot resource. For more information, see [Snapshots](/docs/compute/concepts/snapshot). */
export interface Snapshot {
  $type: "yandex.cloud.compute.v1.Snapshot";
  /** ID of the snapshot. */
  id: string;
  /** ID of the folder that the snapshot belongs to. */
  folderId: string;
  createdAt?:
    | Date
    | undefined;
  /** Name of the snapshot. 1-63 characters long. */
  name: string;
  /** Description of the snapshot. 0-256 characters long. */
  description: string;
  /** Resource labels as `key:value` pairs. Maximum of 64 per resource. */
  labels: { [key: string]: string };
  /** Size of the snapshot, specified in bytes. */
  storageSize: number;
  /** Size of the disk when the snapshot was created, specified in bytes. */
  diskSize: number;
  /**
   * License IDs that indicate which licenses are attached to this resource.
   * License IDs are used to calculate additional charges for the use of the virtual machine.
   *
   * The correct license ID is generated by the platform. IDs are inherited by new resources created from this resource.
   *
   * If you know the license IDs, specify them when you create the image.
   * For example, if you create a disk image using a third-party utility and load it into Object Storage, the license IDs will be lost.
   * You can specify them in the [yandex.cloud.compute.v1.ImageService.Create] request.
   */
  productIds: string[];
  /** Current status of the snapshot. */
  status: Snapshot_Status;
  /** ID of the source disk used to create this snapshot. */
  sourceDiskId: string;
}

export enum Snapshot_Status {
  STATUS_UNSPECIFIED = 0,
  /** CREATING - Snapshot is being created. */
  CREATING = 1,
  /** READY - Snapshot is ready to use. */
  READY = 2,
  /** ERROR - Snapshot encountered a problem and cannot operate. */
  ERROR = 3,
  /** DELETING - Snapshot is being deleted. */
  DELETING = 4,
  UNRECOGNIZED = -1,
}

export function snapshot_StatusFromJSON(object: any): Snapshot_Status {
  switch (object) {
    case 0:
    case "STATUS_UNSPECIFIED":
      return Snapshot_Status.STATUS_UNSPECIFIED;
    case 1:
    case "CREATING":
      return Snapshot_Status.CREATING;
    case 2:
    case "READY":
      return Snapshot_Status.READY;
    case 3:
    case "ERROR":
      return Snapshot_Status.ERROR;
    case 4:
    case "DELETING":
      return Snapshot_Status.DELETING;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Snapshot_Status.UNRECOGNIZED;
  }
}

export function snapshot_StatusToJSON(object: Snapshot_Status): string {
  switch (object) {
    case Snapshot_Status.STATUS_UNSPECIFIED:
      return "STATUS_UNSPECIFIED";
    case Snapshot_Status.CREATING:
      return "CREATING";
    case Snapshot_Status.READY:
      return "READY";
    case Snapshot_Status.ERROR:
      return "ERROR";
    case Snapshot_Status.DELETING:
      return "DELETING";
    case Snapshot_Status.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Snapshot_LabelsEntry {
  $type: "yandex.cloud.compute.v1.Snapshot.LabelsEntry";
  key: string;
  value: string;
}

function createBaseSnapshot(): Snapshot {
  return {
    $type: "yandex.cloud.compute.v1.Snapshot",
    id: "",
    folderId: "",
    createdAt: undefined,
    name: "",
    description: "",
    labels: {},
    storageSize: 0,
    diskSize: 0,
    productIds: [],
    status: 0,
    sourceDiskId: "",
  };
}

export const Snapshot = {
  $type: "yandex.cloud.compute.v1.Snapshot" as const,

  encode(message: Snapshot, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.folderId !== "") {
      writer.uint32(18).string(message.folderId);
    }
    if (message.createdAt !== undefined) {
      Timestamp.encode(toTimestamp(message.createdAt), writer.uint32(26).fork()).ldelim();
    }
    if (message.name !== "") {
      writer.uint32(34).string(message.name);
    }
    if (message.description !== "") {
      writer.uint32(42).string(message.description);
    }
    Object.entries(message.labels).forEach(([key, value]) => {
      Snapshot_LabelsEntry.encode(
        { $type: "yandex.cloud.compute.v1.Snapshot.LabelsEntry", key: key as any, value },
        writer.uint32(50).fork(),
      ).ldelim();
    });
    if (message.storageSize !== 0) {
      writer.uint32(56).int64(message.storageSize);
    }
    if (message.diskSize !== 0) {
      writer.uint32(64).int64(message.diskSize);
    }
    for (const v of message.productIds) {
      writer.uint32(74).string(v!);
    }
    if (message.status !== 0) {
      writer.uint32(80).int32(message.status);
    }
    if (message.sourceDiskId !== "") {
      writer.uint32(90).string(message.sourceDiskId);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Snapshot {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSnapshot();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.folderId = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.createdAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.name = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.description = reader.string();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          const entry6 = Snapshot_LabelsEntry.decode(reader, reader.uint32());
          if (entry6.value !== undefined) {
            message.labels[entry6.key] = entry6.value;
          }
          continue;
        case 7:
          if (tag !== 56) {
            break;
          }

          message.storageSize = longToNumber(reader.int64() as Long);
          continue;
        case 8:
          if (tag !== 64) {
            break;
          }

          message.diskSize = longToNumber(reader.int64() as Long);
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          message.productIds.push(reader.string());
          continue;
        case 10:
          if (tag !== 80) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        case 11:
          if (tag !== 90) {
            break;
          }

          message.sourceDiskId = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Snapshot {
    return {
      $type: Snapshot.$type,
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      folderId: isSet(object.folderId) ? globalThis.String(object.folderId) : "",
      createdAt: isSet(object.createdAt) ? fromJsonTimestamp(object.createdAt) : undefined,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      labels: isObject(object.labels)
        ? Object.entries(object.labels).reduce<{ [key: string]: string }>((acc, [key, value]) => {
          acc[key] = String(value);
          return acc;
        }, {})
        : {},
      storageSize: isSet(object.storageSize) ? globalThis.Number(object.storageSize) : 0,
      diskSize: isSet(object.diskSize) ? globalThis.Number(object.diskSize) : 0,
      productIds: globalThis.Array.isArray(object?.productIds)
        ? object.productIds.map((e: any) => globalThis.String(e))
        : [],
      status: isSet(object.status) ? snapshot_StatusFromJSON(object.status) : 0,
      sourceDiskId: isSet(object.sourceDiskId) ? globalThis.String(object.sourceDiskId) : "",
    };
  },

  toJSON(message: Snapshot): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.folderId !== "") {
      obj.folderId = message.folderId;
    }
    if (message.createdAt !== undefined) {
      obj.createdAt = message.createdAt.toISOString();
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.labels) {
      const entries = Object.entries(message.labels);
      if (entries.length > 0) {
        obj.labels = {};
        entries.forEach(([k, v]) => {
          obj.labels[k] = v;
        });
      }
    }
    if (message.storageSize !== 0) {
      obj.storageSize = Math.round(message.storageSize);
    }
    if (message.diskSize !== 0) {
      obj.diskSize = Math.round(message.diskSize);
    }
    if (message.productIds?.length) {
      obj.productIds = message.productIds;
    }
    if (message.status !== 0) {
      obj.status = snapshot_StatusToJSON(message.status);
    }
    if (message.sourceDiskId !== "") {
      obj.sourceDiskId = message.sourceDiskId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Snapshot>, I>>(base?: I): Snapshot {
    return Snapshot.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Snapshot>, I>>(object: I): Snapshot {
    const message = createBaseSnapshot();
    message.id = object.id ?? "";
    message.folderId = object.folderId ?? "";
    message.createdAt = object.createdAt ?? undefined;
    message.name = object.name ?? "";
    message.description = object.description ?? "";
    message.labels = Object.entries(object.labels ?? {}).reduce<{ [key: string]: string }>((acc, [key, value]) => {
      if (value !== undefined) {
        acc[key] = globalThis.String(value);
      }
      return acc;
    }, {});
    message.storageSize = object.storageSize ?? 0;
    message.diskSize = object.diskSize ?? 0;
    message.productIds = object.productIds?.map((e) => e) || [];
    message.status = object.status ?? 0;
    message.sourceDiskId = object.sourceDiskId ?? "";
    return message;
  },
};

messageTypeRegistry.set(Snapshot.$type, Snapshot);

function createBaseSnapshot_LabelsEntry(): Snapshot_LabelsEntry {
  return { $type: "yandex.cloud.compute.v1.Snapshot.LabelsEntry", key: "", value: "" };
}

export const Snapshot_LabelsEntry = {
  $type: "yandex.cloud.compute.v1.Snapshot.LabelsEntry" as const,

  encode(message: Snapshot_LabelsEntry, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Snapshot_LabelsEntry {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSnapshot_LabelsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Snapshot_LabelsEntry {
    return {
      $type: Snapshot_LabelsEntry.$type,
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: Snapshot_LabelsEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Snapshot_LabelsEntry>, I>>(base?: I): Snapshot_LabelsEntry {
    return Snapshot_LabelsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Snapshot_LabelsEntry>, I>>(object: I): Snapshot_LabelsEntry {
    const message = createBaseSnapshot_LabelsEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

messageTypeRegistry.set(Snapshot_LabelsEntry.$type, Snapshot_LabelsEntry);

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in Exclude<keyof T, "$type">]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P> | "$type">]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = date.getTime() / 1_000;
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { $type: "google.protobuf.Timestamp", seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function longToNumber(long: Long): number {
  if (long.gt(globalThis.Number.MAX_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  return long.toNumber();
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
